### ISSUE TITLE
incorrect attach version

### ISSUE THREAD

**Issue by wlnirvana** [gluonhq/ChatApp#34]
The project uses 4.0.8:

https://github.com/gluonhq/ChatApp/blob/d92e136373bc4c9b9a80c61fcf1f690e4c7a6521/pom.xml#L28

But the latest published at, e.g. https://nexus.gluonhq.com/nexus/content/repositories/releases/com/gluonhq/attach/util/ is 4.0.6

**Comment by abhinayagarwal** [comment]
Attach is now released to Maven Central. This has been taken care of in #35
